### ISSUE TITLE
Licenses with '"approved": "unknown"' in unified list, are not highlighted in output warning lists

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#101]
I've got a project with a dependency on a module that has the ISC license. This license is in the [default-whitelist.json](https://github.com/bucharest-gold/license-reporter/blob/master/lib/resources/default-whitelist.json#L134), but in the [default-unifiedlist.json](https://github.com/bucharest-gold/license-reporter/blob/master/lib/resources/default-unifiedlist.json#L2557), its approval status is set to "unknown".

In the output of the tool, after the XML contents, I see two WARNING lists: "UNKNOWN LICENSES" and "WHITE-LISTED LICENSES". The ISC license is detected properly, and it's "known", so it's not in the first list. The "approval" status is not "yes", so it's not in the second list.

Such licenses seem to have kind of a vague status, so I think they should be highlighted in the output, maybe more so than approved licenses. What do you think?

**Comment by grdryn** [comment]
Hmm, in another case I see an ISC-licensed dependency showing up in the UNKNOWN LICENSES list. I'm not sure why one would and another wouldn't.

**Comment by danbev** [comment]
@grdryn Either the `default-unifiedlist.json` or the `default-whitelist.json` is used, but not at the same time. The former is enabled using the `--unifiedlist`. 

We might remove the whitelist/blacklist options but those were the original requirements and for now they are kept. Let me know if there is still an issue here and I'll take a closer look. Thanks

**Comment by grdryn** [comment]
@danbev ah right, thanks. I've been missing the `--unifiedlist` param. When I give that, I see the license in the output.

With that param passed though, the output looks slightly different: where there was previously the "UNKNOWN LICENSES" list, and the "WHITE LISTED LICENSES" list, now there's the "UNKNOWN LICENSES" list, and everything else is grouped together without any delimiters. I assume that's expected, just thought I'd point it out. It looks like there could be subsections of that though, because it looks like there's more than one alphabetized list there.

**Comment by danbev** [comment]
@grdryn Is it alright if we close this issue and open a new one if you think there is an issue here?

**Comment by grdryn** [comment]
@danbev Yeah sure, go for it. I'll leave it to you to decide if there's an issue with the scenario that I outlined in my most recent comment. 👍
