### ISSUE TITLE
Update xml format

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/license-reporter#105]
There has been a request to change the xml format to:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<licenseSummary>
  <dependencies>
    <dependency>
      <packageName>...</packageName>
      <version>...</version>
      <licenses>
        <license>
          <name>...</name>
          <url>...</url>
        </license>
      </licenses>
    </dependency>
   ...
  </dependencies>
</licenseSummary>
```

**Comment by vibe13** [comment]
@danbev yes the format you provided is the suggested format (with the minimal differences) for non Maven projects, which has instead the suggested format below:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<licenseSummary>
  <dependencies>
    <dependency>
      <groupId>...</groupId>
      <artifactId>...</artifactId>
      <version>...</version>
      <licenses>
        <license>
          <name>...</name>
          <url>...</url>
          <distribution>repo</distribution>
        </license>
      </licenses>
    </dependency>
    ...
  </dependencies>
</licenseSummary>
```

**Comment by danbev** [comment]
@vibe13 At the moment there is nothing identifying the project that this is being run on. This might not be an issue when running the tool and storing the xml somewhere inside the project. But when merging two xmls, currently there will only be a licenseSummary element for each project but not the name of the project. 
Would it be alright to add an element, something like:
```xml
<licenseSummary>
    <project>license-reporter</project>
    <dependencies>
    ....
```
