### ISSUE TITLE
Improve unit test for unifiedlist

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/license-reporter#106]
Currently there is only a single test for the unified list functionality. After updating the xml format in #105 all test pass but the code in unifiedlist.json depends on the old format. A single test was added as part of #105 but this task should take a look and see if there is more that needs to be covered.

**Comment by helio-frota** [comment]
I extracted the code into functions and removed this unnecessary `new Set()` [here](https://github.com/bucharest-gold/license-reporter/blob/master/lib/unifiedlist.js#L57)  and [here](https://github.com/bucharest-gold/license-reporter/blob/master/lib/unifiedlist.js#L67). 

I'm still writing more tests but also trying to remember why [this](https://github.com/bucharest-gold/license-reporter/blob/master/lib/unifiedlist.js#L12) starts with `approved: false`.
I'm going to send a PR tomorrow.

**Comment by helio-frota** [comment]
Seems like the property `approved: false` makes no much sense.
This is the flow, also removing the property, affects nothing.

```console
+-----+  call   +------------------------------+  print to   +--------+
| foo | ------> | unifiedlist.check(xmlObject) | ----------> | stdout |
+-----+         +------------------------------+             +--------+
```
