### ISSUE TITLE
License URL should be referenced from the JSON file

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#110]
Currently our license URL is pulled from an absolute path, which can often point to a location that is not accessible to the consumer of the XML.

Within the Good/Bad license.json file there exists a URL to a remote location where the license is kept. Our URL element should be pointing to that.

ping @danbev

**Comment by danbev** [comment]
I think it might be a good time to remove the white and black list options at the same time as doing this. The only URL available is in the unified.json format.  @helio-frota What do you think?

**Comment by helio-frota** [comment]
@danbev I agree.
Also not only to cleanup more the code, but to avoid misunderstanding with similar features.
:+1:

**Comment by lgriffin** [comment]
Also worth noting that @balunasj helped to get the good/bad JSON file to a neutral enough position that we could use it in the open. It might be worth associating that file with the project as well so that end users know where it came from and can modify it for their own needs then :)
