### ISSUE TITLE
Local Licenses stored within a license folder

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#117]
Within the HTML file that is generated we have the concept of a remote and a local license.

The remote license is a reference to the URL entity in the canonical names mapping file.
The local license should point to a local, relative path reference

Other products distribute a license folder which contains:
- a license.xml file
- a license.html file
- a suite of license.txt files

The license.txt files are the collection of relevant license files for that particular run, named appropriately. For example:
- Apache2.txt --> which is the stock text from the remote license link
- MIT.txt --> which is the stock text from the remote license link

This removes the variance in license texts which could occur from referencing license location files which might vary from package.json references to the License files themselves. It helps keep the wording and interpretation consistent.

The HTML file would then reference the local license.txt for the appropriate license, thus ensuring an accurate and consistent wording.

This would be a very welcome enhancement.

**Comment by lgriffin** [comment]
Update on this would be to directly reference the text as it appears in the dependency and still port it to a local position. So as a made up example you might have a dependency  which appears in ./node_modules/dependency1/license which has an Apache 2 license

We should be putting that license in a folder, alongside the HTML file and name it appropriately e.g. dependency1_Apache2.txt

Rationale: They might not have copied the full license, or inserted additions into the text. Our HTML report should be pointing at the official Apache 2 license via the remote URL and the local URL should be pointing to the local flavour for the dependency1 modules text. 

Happy to clarify more!

**Comment by lgriffin** [comment]
Given that the rest of Middleware are going with the original view I mentioned when I opened this ticket, I think we should go for that approach rather than the unique local license (which was my 2nd comment). Obviously if the work is done, the unique license is more optimal to me longer term and may be a more formal request longer time.

From my mail:

> We take the remote license URL and download a singular copy of it and use the canonical name on the local license. This ensures that if we have X number of licenses of the same type, that we only have 1 local license to reference to all X.

**Comment by helio-frota** [comment]
@lgriffin I think we can close this issue now

now we have:
1. A `license` folder along side the `license.html` file
2. The original license files from each dependency inside this ^ license folder following the name `project_license.txt`
3. The `local license` column from `license.html` pointing to the `license/project_license.txt` for each dependency.

Example using szero: 

![screenshot from 2017-10-17 14-50-10](https://user-images.githubusercontent.com/6443576/31681374-70ce0aea-b34d-11e7-852c-be3c5f431a5c.png)

**Comment by helio-frota** [comment]
@lgriffin thanks for the help and clarification!

**Comment by lgriffin** [comment]
Hi @helio-frota this looks great and protects us from a future request from Legal, super job!

I just have one minor comment. The pathway on the sample you provided might not be accessible in the local licenses link as you reference /home. Could the URL element be a relative link? Considering the html file will live in the license folder it should be ./ accessible.

**Comment by helio-frota** [comment]
@lgriffin got it !
thanks

**Comment by helio-frota** [comment]
![screenshot from 2017-10-17 16-46-42](https://user-images.githubusercontent.com/6443576/31686085-9afe9cae-b35b-11e7-8e43-2d0559957fa8.png)

and link pointing to the file

![screenshot from 2017-10-17 16-46-57](https://user-images.githubusercontent.com/6443576/31686107-a79e1642-b35b-11e7-9a10-d757b472770a.png)

**Comment by lgriffin** [comment]
That looks perfect 👍 

Great work!
