### ISSUE TITLE
Output to HTML is broken

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#118]
Running:

`license-reporter --file license.html --all --unifiedlist --silent --html`

or any of the combinations that result in a html file being produced is currently broken. The HTML file is not populating.

**Comment by helio-frota** [comment]
@lgriffin the html report is working again.

![report](https://user-images.githubusercontent.com/6443576/30272114-4ff7c77a-96c9-11e7-85ce-2cc4b0ff80bd.png)

We can close this issue and open a new one related to the last column `Local Licenses`.
I'll grab more information about that part to understand better.

**Comment by lgriffin** [comment]
That's great thanks @helio-frota . Agreed we should open a new issue about the Local License links

**Comment by lgriffin** [comment]
Actually @helio-frota I just ran it locally and I get this error:

```
> Error: No URL was found for [UNKNOWN, UNKNOWN]
  at Error (native)
    at Object.urlForName (/Users/lgriffin/WORK/license-reporter/lib/unifiedlist.js:103:9)
```

Looks like an edge case issue for Unknown which obviously would not have a URL to reference.

**Comment by helio-frota** [comment]
> Looks like an edge case issue for Unknown which obviously would not have a URL to reference.

Makes sense, btw, thanks for report !
