### ISSUE TITLE
Add documentation to indicate what files are checked as part of generating the license.xml

### ISSUE THREAD

**Issue by ccfoley** [bucharest-gold/license-reporter#119]
It may be helpful for user to know what files are checked by the license-reporter and the order in which the reporter looks for them, e.g. package.json, LICENSE and COPYING. Also if the tool continues to search if it finds a file or not.
This will just give a better understanding of how the tool works.

**Comment by helio-frota** [comment]
@ccfoley The docs for this part can be found here:
https://github.com/bucharest-gold/license-reporter#how-licenses-are-found-in-files
thanks for the suggestion!
