### ISSUE TITLE
Clarify usage of white/black/unified list parameters

### ISSUE THREAD

**Issue by ccfoley** [bucharest-gold/license-reporter#121]
Currently we have the following command line parameters, whitelist, blacklist and unifiedlist. Can all of these be fed in together, presumably not? If we think that whitelist and blacklist are not necessary now and unifiedlist covers us, maybe we can consider removing them (from the command line options at a min)?

Might also be worth adding to the documentation that a user can feed in their own unifiedlist file if they have one, otherwise the default file (lib/resources/default-unifiedlist.json) is used.

**Comment by helio-frota** [comment]
> ... maybe we can consider removing them 

yup was removed!

> Might also be worth adding to the documentation that a user can feed in their own unifiedlist file if they have one, otherwise the default file (lib/resources/default-unifiedlist.json) is used.

Great, thanks for the suggestion!
