### ISSUE TITLE
Update documentation to populate <url> with link to a remote license

### ISSUE THREAD

**Issue by ccfoley** [bucharest-gold/license-reporter#122]
In some of the examples in the documentation, the <url> tag shows a relative link, e.g. 

`            <licenses>
                <license>
                    <name>MIT</name>
                    <url>/work/bucharest-gold/szero/node_modules/commander/LICENSE</url>
                </license>
            </licenses>`

It would be good to show the link coming form the  lib/resources/default-unifiedlist.json file, e.g.

`"3dfx Glide License": {
        "fedora_abbrev": "Glide",
        "fedora_name": "3dfx Glide License",
        "id": "1",
        "license_text": "",
        "approved": "yes",
        "spdx_abbrev": "Glide",
        "spdx_name": "3dfx Glide License",
        "url": "http://www.users.on.net/~triforce/glidexp/COPYING.txt"
    },`

**Comment by helio-frota** [comment]
Doc updated, thanks!

interesting the `all.xml` was reduced a lot for that example with szero - 664K to 188K
https://github.com/bucharest-gold/license-reporter/commit/dd56e7d60e333dc67ee4f419aa9d8e818d33d298#diff-04c6e90faac2675aa89e2176d2eec7d8R256
