### ISSUE TITLE
Error when license contains comma

### ISSUE THREAD

**Issue by pb82** [bucharest-gold/license-reporter#124]
The following exception is thrown when a license contains a comma, e.g. `Apache License, Version 2.0`:

```
/Users/peter/work/license-reporter/lib/unifiedlist.js:103
  throw Error(`No URL was found for [${name}]`);
  ^

Error: No URL was found for [UNKNOWN, UNKNOWN]
```

It can be reproduced by running the license reporter on a project that has a dependency to `rx-lite`.

It looks like the license-reporter tries to handle multiple comma separated licenses here: https://github.com/bucharest-gold/license-reporter/blob/master/lib/canonical-name.js#L6

However https://github.com/bucharest-gold/license-reporter/blob/master/lib/unifiedlist.js#L97 doesn't take this into account. It only checks for a single `UNKNOWN`.

Should multiple comma separated licenses be supported? If not, maybe we can remove https://github.com/bucharest-gold/license-reporter/blob/master/lib/canonical-name.js#L6 and just return `get(name)` here?

**Comment by helio-frota** [comment]
@pb82 thanks for bug report !

reproduced here:

```console
[hf@localhost project-foo]$ npm install rx-lite -S
npm WARN project-foo@1.0.0 No description
npm WARN project-foo@1.0.0 No repository field.

+ rx-lite@4.0.8
added 1 package in 2.168s
[hf@localhost project-foo]$ license-reporter 
/home/hf/d/license-reporter/lib/unifiedlist.js:103
  throw Error(`No URL was found for [${name}]`);
  ^

Error: No URL was found for [UNKNOWN, UNKNOWN]
    at Object.urlForName (/home/hf/d/license-reporter/lib/unifiedlist.js:103:9)
    at entry (/home/hf/d/license-reporter/bin/cli.js:53:27)
    at addLicenseEntry (/home/hf/d/license-reporter/bin/cli.js:76:45)
    at xmlObjectData (/home/hf/d/license-reporter/bin/cli.js:128:9)
    at checker.init (/home/hf/d/license-reporter/bin/cli.js:160:17)
    at /home/hf/d/license-reporter/node_modules/license-checker/lib/index.js:373:9
    at /home/hf/d/license-reporter/node_modules/read-installed/read-installed.js:142:5
    at /home/hf/d/license-reporter/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/license-reporter/node_modules/slide/lib/async-map.js:47:24)
    at /home/hf/d/license-reporter/node_modules/read-installed/read-installed.js:263:14
```

**Comment by pb82** [comment]
@danbev @helio-frota Thank you!
