### ISSUE TITLE
Error "No URL was found for [UNKNOWN, UNKNOWN]"

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#127]
Details here: https://github.com/bucharest-gold/license-reporter/issues/118#issuecomment-328499997

**Comment by helio-frota** [comment]
Looking again the code,  I'm not 100% sure if this is a bug.

1. if we just print the message to console instead throw the error we have something like this:

> I've commented all the code, just sending to output the message

```
[hf@localhost project-foo]$ license-reporter --html
No URL was found for [Apache License 2.0]
No URL was found for [UNKNOWN]
No URL was found for [UNKNOWN]
<?xml version='1.0'?>
<licenseSummary>
    <project>project-foo</project>
    <version>1.0.0</version>
    <dependencies>
```

2. If not throw the error then something wrong can mean something right.

Question is good to keep throwing the error ( that will break the user build ) or just print as "warning" to the stdout ?

**Comment by helio-frota** [comment]
> ...but when we've seen problems, it breaks our builds.

https://github.com/bucharest-gold/license-reporter/issues/132

**Comment by danbev** [comment]
> Question is good to keep throwing the error ( that will break the user's build ) or just print as "warning" to the stdout ?

If this is an issue for users that I think perhaps just returning 'UNKNOWN' for the url if is is not matched would make sense.

**Comment by helio-frota** [comment]
@danbev :+1:  Going to close this and create a new one. Thanks!
