### ISSUE TITLE
Error: "Could not find name map file"

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#131]
@helio-frota we see this error after 89cb27439a86b675bc452c7e51e8c20b2cb51173 (latest commit on master, as of writing), but not before it:

```
$ license-reporter --ignore-version-range --all --silent --file licenses.xml
Could not find name map file:  /home/grdryn/src/fheng/my-project/license-reporter/lib/resources/default-canonical-names.json
```

It looks like it's looking in the wrong place for `lib/resources/default-canonical-names.json`.

**Comment by helio-frota** [comment]
@grdryn thanks for report !
hm this also means we need more unit tests

**Comment by helio-frota** [comment]
this is directly related to the text that appears on help : /
I mean seems like we need the full path to show on `--help` 
```
  --name-map              a file/url containing a mapping of license names
        [default: "license-reporter/lib/resources/default-canonical-names.json"]
```

**Comment by helio-frota** [comment]
@grdryn fixed, thanks!
