### ISSUE TITLE
Either start publishing to npmjs, or have tags here, for stable releases

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#132]
We use this in many of our builds now in the FeedHenry project repos (and lots of internal projects also), but we're currently using it as it is here: https://github.com/feedhenry/fh-pipeline-library/blob/master/vars/npmInstall.groovy#L12..L13

We used to use master, rather than the hardcoded commit sha1 that you see there, but when we've seen problems, it breaks our builds. If there was something more stable than master, like a release on npmjs, or here on GitHub via a git tag, that would be a great help to us.

**Comment by danbev** [comment]
We have tagged the current master:
https://github.com/bucharest-gold/license-reporter/tree/v0.3.0

And also published to the private repository:
```console
$ npm install license-reporter -g --registry http://npm.skunkhenry.com
```

We have not published to the public npm repository yet as I want to double check that this is alright to do. @balunasj mentioned an ongoing legal inquiry which we'd like to wait for.

**Comment by helio-frota** [comment]
closing:
https://www.npmjs.com/package/license-reporter
