### ISSUE TITLE
Crashes if there are no dependencies / no node_modules directory

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#137]
If there aren't any dependencies, then license-reporter will crash with something similar to the following:

```
$ license-reporter --ignore-version-range --all --silent --file licenses.xml
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/grdryn/src/fheng/fh-template-apps/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at html.parse.then.Object.keys.filter.content (/home/grdryn/src/bucharest-gold/licenser/bin/cli.js:175:22)
    at Object.run (/home/grdryn/src/bucharest-gold/licenser/bin/cli.js:220:7)
    at Object.<anonymous> (/home/grdryn/src/bucharest-gold/licenser/bin/license-reporter:88:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

It should ideally succeed, just reporting on the project itself.

We encountered this because we've started running the tool after installing production dependencies, but before installing dev dependencies (we did this initially to work around one of the other bugs, but we're sticking to it now because we believe it's what we want). In one project, we've got dev dependencies but no production dependencies -- so when we go to run this, there's no node_modules directory, and our builds fail on this.

**Comment by grdryn** [comment]
@helio-frota 👆

**Comment by helio-frota** [comment]
@grdryn thanks for report !

> If there aren't any dependencies, then license-reporter will crash with something similar to the following:

yah, this needs to be fixed.

> It should ideally succeed, just reporting on the project itself.

This case we need to think a bit more. We need to do some kind of workaround because the tool that scans the dependencies needs `node_modules` directory.

> ...and our builds fail on this.

One of the main focus of the workaround is to avoid this.

**Comment by helio-frota** [comment]
@grdryn can you please test again ? Thanks!
https://github.com/bucharest-gold/license-reporter/commit/210ca536c039b4c714aab7a4c5cd93ea98d75064

**Comment by grdryn** [comment]
@helio-frota I've pulled again and tried just now. It doesn't crash any longer, so thanks! :)

It doesn't give a license file though, and instead gives the following message:

```
$ license-reporter --ignore-version-range --all --silent --file licenses.xml
You need to run 'npm install' before search for license information.
```

**Comment by helio-frota** [comment]
@grdryn yes.

> It should ideally succeed, just reporting on the project itself.

I'll try something about it, but this is not in the plans. I think we can only display the project name, version and license (if found) on package.json of the root/current project. To generate the license.xml

Going to close this and open a new one for this.
