### ISSUE TITLE
When no node_modules , generate a licence.xml with medatadata from current project.

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#139]
get the project name, version and license (if found) on package.json of the root/current project. To generate the license.xml.

mode details here: #137

**Comment by helio-frota** [comment]
how to reproduce:

```bash
mkdir aaa ; cd aaa
npm init -y
license-reporter --file=license.xml
```

output:
```console
<?xml version='1.0'?>
<licenseSummary>
    <project>aaa</project>
    <version>1.0.0</version>
    <dependencies/>
    <license>ISC</license>
</licenseSummary>
```

@grdryn https://github.com/bucharest-gold/license-reporter/commit/5a1b1aeb0ffe65136dab0d83e10a722f32d5dfc2

**Comment by grdryn** [comment]
@helio-frota looks good, thanks!
