### ISSUE TITLE
Use a custom unified-list ?

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#146]
Currently `--unified-list` is the default flow because black/white list was removed.
But we are not able to select a custom unified list from a json file.

1. This feature was implemented for black/white lists.
2. The structure of b/w lists was simple, only name and value.

If we plan to provide a custom unified list we need to add a more of complexity to ensure the JSON structure is the correct and have the correct fields. 

Question 1: This is really needed ?

Current structure:

```
"Foo License": {
    "fedora_abbrev": "Foo",
    "fedora_name": "Bar",
    "id": "1",
    "license_text": "",
    "approved": "yes",
    "spdx_abbrev": "FoBar",
    "spdx_name": "barFoo",
    "url": "http://fobar.org"
},
```

Question 2: If the user to provide a weird structure like this ?

```
"Foo License": {
    "id": "1",
    "text": "",
    "cool": "yes",
    "name": "barFoo",
    "url": "http://fobar.org"
},
```

related to #121

**Comment by danbev** [comment]
I'd say a user should copy the default unified-list.json and modify it to suite their needs. If they change things to much then it might not work.

**Comment by helio-frota** [comment]
I agree with only modifying the values. So then we can write a function to ensure the structure has that exactly 8 fields and the license name.

**Comment by helio-frota** [comment]
thanks! closing now
