### ISSUE TITLE
Doesn't seem to handle license field in package.json containing '(MIT OR Apache-2.0)'

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#173]
```
$ npm show --json JSONStream@0.10.0 | jq '.license'
"(MIT OR Apache-2.0)"
```

This dependency gets displayed as 'UNKNOWN' by license-reporter.

**Comment by helio-frota** [comment]
@grdryn thanks for report this.
I'm not 100% sure if license-reporter should handle this kind of license.
IMO it should be `UNKNOWN`, but is just a personal view, not a requirement.

**Comment by helio-frota** [comment]
@grdryn looking  a bit more I found that is something wrong.
We are using this: https://github.com/davglass/license-checker
that uses this: https://github.com/kemitchell/spdx.js
And after test with this code the result was `true` (valid):

```js
const spdx = require('spdx');
console.log(spdx.valid('MIT OR Apache-2.0'), 'MIT OR Apache-2.0');
console.log(spdx.valid('(MIT OR Apache-2.0)'), '(MIT OR Apache-2.0)');
```

```console
$ node foo.js
true 'MIT OR Apache-2.0'
true '(MIT OR Apache-2.0)'
```

**Comment by lance** [comment]
I'm confused, though. MIT and Apache-2 are two different licenses with two different sets of permissions. They are similar, but distinctly different. What would the expected license be in this case?

**Comment by helio-frota** [comment]
@lance  I have no idea 

**JSONStream:**
`OR` on README.md
https://github.com/dominictarr/JSONStream#license
`OR` on package.json
https://github.com/dominictarr/JSONStream/blob/master/package.json#L10

**vis:**
`AND` on README.md
https://github.com/almende/vis#license
`OR` on package.json
https://github.com/almende/vis/blob/master/package.json#L6

Maybe for the legal `AND` or `OR` are the same ? I dunno.

**Comment by helio-frota** [comment]
btw, for this particular issue we need to detect where `(MIT OR Apache-2.0)` is discarded (by license-reporter or license-checker), because spdx.js output this as `valid`.

**Comment by helio-frota** [comment]
license-checker is not discarding :

```
{ 'JSONStream@1.3.1': 
   { licenses: '(MIT OR Apache-2.0)',
     repository: 'https://github.com/dominictarr/JSONStream',
...
```

This means is something wrong with license-reporter, then I'm going to change the label from `warning` to `bug`

**Comment by helio-frota** [comment]
@grdryn @lance 
Just found, this is because `(MIT OR Apache-2.0)` is not part of  `canonical names`
https://github.com/bucharest-gold/license-reporter/blob/master/lib/resources/default-canonical-names.json

@lgriffin In this case we can close this issue or we are going to add an exception to `(MIT OR Apache-2.0)` or it will be part of canonical names file ?

Thanks!

**Comment by lgriffin** [comment]
Hmmm surely they should be in the master JSON file. Let me check with Andrea tomorrow.

**Comment by lgriffin** [comment]
Andrea is raising the dual license issue so for now this is not going to be resolved. Logic should be there to handle this scenario in time as it's within the specs, just not reflected in the license naming files.

**Comment by helio-frota** [comment]
For dual license the result is :
Thanks !

```xml
<?xml version='1.0'?>
<licenseSummary>
    <project>foo-project</project>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <packageName>JSONStream</packageName>
            <version>1.3.1</version>
            <licenses>
                <license>
                    <name>(MIT OR Apache-2.0)</name>
                    <url>UNKNOWN</url>
                </license>
            </licenses>
        </dependency>
    </dependencies>
</licenseSummary>
```
landed: https://github.com/bucharest-gold/license-reporter/commit/a9de82bafcb6f3ddba2f6cea7b71111f6e0cad62

**Comment by vibe13** [comment]
Hi @grdryn @helio-frota @lance @lgriffin, I had a reply from Legal. It is fine to report the 2 different licenses separately in the html and xml files, each one pointing to its own license text. Also, for the happiness of mathematicians, "the 'AND' should just be treated as 'OR'". :-). So xml should be similar to:

```
<?xml version='1.0'?>
<licenseSummary>
    <project>foo-project</project>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <packageName>JSONStream</packageName>
            <version>1.3.1</version>
            <licenses>
                <license>
                    <name>MIT</name>
                    <url>https://opensource.org/licenses/MIT</url>
                </license>
                <license>
                    <name>Apache-2.0</name>
                    <url>http://www.apache.org/licenses/LICENSE-2.0</url>
                </license>
            </licenses>
        </dependency>
    </dependencies>
</licenseSummary>
```
Thanks
Andrea

**Comment by lgriffin** [comment]
Thanks Andrea! I'm unsure what impact this has on our HTML, possibly none

Would it make a difference if we reported the same dependency twice i.e. have 2x dependency versions for JSONStream in the above example?

Just want to give the devs some options here.

**Comment by vibe13** [comment]
Hi Leigh, no, I really don't think it would be an issue, if that makes it easier for you, go ahead!

**Comment by lgriffin** [comment]
Perfect I hope that the way you outlined is fine just wanted alternatives! Thanks @vibe13

**Comment by helio-frota** [comment]
related to #179
