### ISSUE TITLE
xml file no longer gets created (at least I can't find it)

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#175]
```
license-reporter --ignore-version-range --all --file licenses.xml
```

With the above command, using the latest commit on master, I no longer get a file called 'licenses.xml'. On the `v0.3.0` tag, the file gets created just fine.

**Comment by helio-frota** [comment]
@grdryn it was necessary to make a modification in the arguments, from `--xml` instead `--file`

Because now we have the possibility to create `json` and `yaml`.
```
  --xml                   xml file to store the license information in  [string]
  --json                  json file to store the license information in [string]
  --yaml                  yaml file to store the license information in [string]
```

**Comment by helio-frota** [comment]
closing.
