### ISSUE TITLE
Dual License clarification

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#179]
Awaiting clarification on dual licenses in our official canonical naming file. Will update this when Legal and Andrea come back to us!

**Comment by helio-frota** [comment]
good progress on it:

using a `foo-project`:

```console
[hf@localhost foo-project]$ license-reporter --html
<?xml version='1.0'?>
<licenseSummary>
    <project>foo-project</project>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <packageName>JSONStream</packageName>
            <version>1.3.1</version>
            <licenses>
                <license>
                    <name>MIT License</name>
                    <url>http://www.opensource.org/licenses/MIT</url>
                </license>
            </licenses>
        </dependency>
        <dependency>
            <packageName>JSONStream</packageName>
            <version>1.3.1</version>
            <licenses>
                <license>
                    <name>Apache License 2.0</name>
                    <url>http://www.apache.org/licenses/LICENSE-2.0</url>
                </license>
            </licenses>
        </dependency>
    </dependencies>
</licenseSummary>
========= APPROVED LICENSES        ==========
name: JSONStream , version: 1.3.1 , licenses: Apache License 2.0
name: JSONStream , version: 1.3.1 , licenses: MIT License
========= APPROVED LICENSES        ==========
```

And the generated HTML shows `JSONStream_MIT License.txt` but in fact (when click on it ) is the Apache License file.
![screenshot from 2017-10-24 20-41-38](https://user-images.githubusercontent.com/6443576/31973381-fe215290-b8fb-11e7-957a-649e1cee7dea.png)

**Comment by helio-frota** [comment]
> And the generated HTML shows JSONStream_MIT License.txt but in fact (when click on it ) is the Apache License file.

This means we need to add: `'No local license could be found for the dependency'` instead.

**Comment by lgriffin** [comment]
Looks good @helio-frota :) 

I did mention to Andrea that we may have scenarios were one of the local licenses are not found. I'm wondering in that case should we tweak the text to indicate that not only the fact that the local text is missing but that it is indeed a dual license e.g. "No local license found as this is a dual license dependency" or words to that affect?

I'm wondering is there a technical reason we don't go down the route of embedding both licenses within the:
`<licenses>` attribute like Andrea mentioned?

Obviously both are correct this is more a curious question :)

**Comment by helio-frota** [comment]
I was able to add both licenses within the `<licenses>` attribute, but the html report is using the data and gets corrupted with glitches.

```
[hf@localhost foo-project]$ license-reporter
<?xml version='1.0'?>
<licenseSummary>
    <project>foo-project</project>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <packageName>JSONStream</packageName>
            <version>1.3.1</version>
            <licenses>
                <license>
                    <name>MIT License</name>
                    <url>http://www.opensource.org/licenses/MIT</url>
                </license>
                <license>
                    <name>Apache License 2.0</name>
                    <url>http://www.apache.org/licenses/LICENSE-2.0</url>
                </license>
            </licenses>
        </dependency>
    </dependencies>
</licenseSummary>
```

**Comment by helio-frota** [comment]
I was working on another branch to solve this kind of problem related with the same data affected by other functions.
https://github.com/helio-frota/license-reporter/tree/pr

( this branch is related to #226 and will need more time )

I'll try to replicate the data that goes to html or try to solve directly, to be able to finish this issue.

**Comment by helio-frota** [comment]
PR sent, 

To not have problems with HTML report we need to duplicate the license as discussed.
( but on console stdout it will continue to print duplicated `<dependency> ` entry, instead 
both licenses within the `<licenses>` attribute )

To show both licenses within the `<licenses>` attribute we need to choose the option to export to file or only to stdout `license-reporter --json` or just `license-reporter`.

This seems to be a side effect of not using commands #226

**Comment by helio-frota** [comment]
@lgriffin 

landed here https://github.com/bucharest-gold/license-reporter/commit/a272cada5b9e3284069b7775a7b5b08581577103

Thanks!

**Comment by helio-frota** [comment]
@lgriffin https://github.com/bucharest-gold/license-reporter/issues/226#issuecomment-342608089

**Comment by helio-frota** [comment]
PR merged, I'm going to close this, but I'll keep on the remaining items
of this comment: https://github.com/bucharest-gold/license-reporter/issues/226#issuecomment-342481041
