### ISSUE TITLE
[Bug] when generating HTML if a LICENSE file is in the root directory

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#183]
If the root directory contains a file called LICENSE (which is very common) and you attempt to generate a HTML file you will get an error. For example I ran this on RainCatcher https://github.com/lgriffin/raincatcher-core

`Error: ENOTDIR: not a directory, open '/Users/lgriffin/GIT_testing/RainCatcher/raincatcher-core/license/tslint_Apache License 2.0.txt'`

It's correct in that it views LICENSE as not being a directory. I'm wondering should the default name be licenses to avoid such a collision or should we allow the user specify the output location folder?

**Comment by lgriffin** [comment]
I opened #184 for this

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/license-reporter/commit/ac49d5ffebbd662ff643f3954e33aaa9c9c287fd
