### ISSUE TITLE
Issue with the Local License Link in the generated HTML

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#185]
When I generate the HTML and click in on the report I see the Local Licenses listed. If I click on any file I get a broken link as an erroneous %2F is inserted instead of a forward slash. Running it in the license-reporter directory can show this bug as it is repeatable on several repositories. Here is an example which links me to:

`file:///Users/lgriffin/GIT_testing/Bucharest/lg/license-reporter/licenses%2Fjsonschema_MIT%20License.txt`

Replacing `%2F` with a simple `/` lands me correctly on the file that's on my disk.

Hopefully a minor change!

**Comment by lgriffin** [comment]
As part of this request I think it would be better to have everything live in the licenses folder. When this gets hooverd up by a Docker image they will have a single folder to look at. Also I want to add license information to other OSS projects I contribute towards and it looks messy when I create a licenses folder (with several .txt files) and then in the root I have a license HTML, XML and CSS file. Could we centralise everything in the licenses folder so that it becomes a one stop shop for developers and keeps the code base clean!

**Comment by helio-frota** [comment]
@lgriffin you right!
I've tested only with firefox, but it not work when using google chrome o_0

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/license-reporter/commit/5ced1416d87c5ed33eb618698e76073390037fa7 thanks!

**Comment by lgriffin** [comment]
Ah excellent, glad I use Chrome to spot it :D 

Thanks for the fast fix and merge @helio-frota

**Comment by helio-frota** [comment]
@lgriffin the files are now centralized on `licenses` directory.
thanks !
