### ISSUE TITLE
[Suggestion] Approved License Check: Clarity on license types flagged as unknown

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#191]
In our unified list we have an approved flag which has 3 values:

- yes (this is a good license)
- no (this is a bad license)
- unknown (we don't know if it is good or bad)

The unknown state with respect to approved or not actually means the following:

> unknown means that we could not match the license against the Fedora list of good and bad ones, and we would need to ask legal for verification. It's also the default value for licenses which we encounter for the first time, and we would need once again the verification from legal.

Currently our logic puts a No and a Yes as a "Not Approved" License. Technically that is not correct. Perhaps we should have a 3rd designation for any license that flags as Unknown. We basically want to alert our users that you should seek clarification if using this particular license as right now we do not know enough about it to say whether it is approved or not. The clarification might come at a later date, in which case the unified list should have the unknown updated to a yes or no. 

So we might have the following output at the end:

=====APPROVED LICENSES=====
Any license that flags as a yes on the approved JSON list

=====NOT APPROVED LICENSES=====
Any license that flags as a no on the approved JSON list

=====CLARIFICATION ADVISED=====
Any license that flags as an unknown on the approved JSON list

Hope that makes sense!

**Comment by vibe13** [comment]
explanation looks good to me! thanks @lgriffin

**Comment by helio-frota** [comment]
landed here: https://github.com/bucharest-gold/license-reporter/commit/8a2846936dbef7c0c000de5ee2333aec84236239
