### ISSUE TITLE
Some README.md files as "License file" even if no # License section is defined.

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#193]
I'm not 100% sure but I think this is from license-checker tool.

example: see the @raincatcher-examples/angularjs-extensions/README.md file, it has no content related with licenses/legal.

In this case we are going to keep the README.md as `License file` ?

**Comment by lgriffin** [comment]
I thought we had agreed not to go to README level. That we look in:

- package.json
- License file

And stop at that point. As we go and have to guess the language. In that case we should be flagging it as Unknown license and alerting the end user (we do this!)

**Comment by helio-frota** [comment]
Good! then we can print a warning `License file not found` when using the `--html` option and the `license file` is a `README.md`

**Comment by helio-frota** [comment]
this message : https://github.com/bucharest-gold/license-reporter/issues/190#issuecomment-338217976

**Comment by helio-frota** [comment]
output:

```console
========= No license file found for==========
@raincatcher-examples/angularjs-extensions
@raincatcher-examples/step-accident
@raincatcher-examples/step-vehicle-inspection
@raincatcher/angularjs-auth-keycloak
@raincatcher/angularjs-auth-passport
@raincatcher/angularjs-http
@raincatcher/angularjs-workflow
@raincatcher/angularjs-workorder
@raincatcher/logger
@raincatcher/step-signature
@raincatcher/wfm
angular-animate
angular-aria
grunt-cli
```

HTML report:

![screenshot from 2017-10-20 12-57-50](https://user-images.githubusercontent.com/6443576/31830347-4e3c37cc-b596-11e7-8c18-149b84c10161.png)

**Comment by lgriffin** [comment]
I think this looks good but N/A in the HTML report could be misleading. This report is viewable by an end customer who might not necessarily have ran the tool to generate it. So they would miss the valuable warning and are blindly looking at the HTML report. Perhaps a 1 liner along the lines of:

"No local license could be found for the dependency" might be more appropriate.

Out of curiosity how does the MIT remote license get discovered in the above scenario you linked?

**Comment by helio-frota** [comment]
> Out of curiosity how does the MIT remote license get discovered in the above scenario you linked?

This is from default-unified-list.json
https://github.com/bucharest-gold/license-reporter/blob/master/lib/resources/default-unified-list.json#L2992-L3000

**Comment by helio-frota** [comment]
this is the code that reads the json file
https://github.com/bucharest-gold/license-reporter/blob/master/lib/file-reader.js#L17-L33

**Comment by lgriffin** [comment]
Right I think I get it as I have the flow in my head right now! So it basically can discover the license in the dependency, it knows that the dependency is MIT (in the above example), it can thus find it in the unified list and record it as being the correct license. However when it comes to populating the local license it cannot get the local license file due to some weirdness with namespaces / references (the bug itself!) and hence printed N/A. Cool thanks for the clarity :)
