### ISSUE TITLE
Raincatcher-portal as example on readme.md ?

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#194]
Why ?

The project `raincatcher-portal` has others points like:

1. namespace `@raincatcher/...` (impacts on file name creation)
2. cases where README.md is used as `licenseFile` property by the license-checker tool.
3. has much more dependencies than genet and szero.
4. The HTML report will be more filled.
5. We may have more "usage" edge cases/ UX issues to solve/look/compare

wdyt @lgriffin ?

**Comment by lgriffin** [comment]
I think a feature rich example is always welcome and show cases more of our edge cases from a usage perspective. Gets my vote :)
