### ISSUE TITLE
Add custom output directory option

### ISSUE THREAD

**Issue by astefanutti** [bucharest-gold/license-reporter#303]
Commands like `save` or `merge` output to `$(pwd)/licenses`. It would be useful to have an option to specify the output directory.

**Comment by helio-frota** [comment]
@astefanutti thanks for the feature suggestion :+1: 
https://github.com/bucharest-gold/license-reporter/commit/691f99c59efb31306063a4d212553ecdb9d6c33a

**Comment by astefanutti** [comment]
@helio-frota thanks for the quick dev! Waiting for the next release to use it!

**Comment by helio-frota** [comment]
( here the instructions, maybe is good to add this on README.md )

The option was added to report, save and merge commands.

example using save and merge:

* creates a `foo.xml` file inside `foo` directory
* creates a `bar.xml` file inside `bar` directory
* merges both XMLs with a `Merge product name`:`FooBar` and file name `foobar.xml` inside the directory `foobar`
```console
license-reporter save --xml="foo" -o="foo"
license-reporter save --xml="bar" -o="bar"
license-reporter merge --mpn="FooBar" --mlx="./foo/foo.xml,./bar/bar.xml" --mo="foobar.xml" --o="foobar"
```

**Comment by helio-frota** [comment]
@astefanutti new version was published
https://www.npmjs.com/package/license-reporter

Sorry the delay.

**Comment by astefanutti** [comment]
@helio-frota thanks for the release and the heads-up!
