### ISSUE TITLE
Update the repo description to say license-reporter instead of licenser

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#80]
I just noticed this, unfortunately it's not something that I can do a drive-by PR to fix. :)

**Comment by danbev** [comment]
@grdryn Thanks, I've updated it now.

**Comment by grdryn** [comment]
@danbev You'll need to fix it again I think: `licenser-reporter` -> `license-reporter` :-)

**Comment by danbev** [comment]
@grdryn Glad I did not close the issue before :) Thanks again!
