### ISSUE TITLE
Metadata about the component that the licenser is running against

### ISSUE THREAD

**Issue by lgriffin** [bucharest-gold/license-reporter#81]
The licenser should include metadata about the component that it is run against. This metadata should be:

- Name of the component
- Version
- License of that component

This looks to be a requirement that is not quiet elicited in the spec but could be coming against us soon.

**Comment by helio-frota** [comment]
@lgriffin 

> component that the licenser is running against

This is the same case of : #139 ?
more details here https://github.com/bucharest-gold/license-reporter/issues/137

thanks!

**Comment by lgriffin** [comment]
I think it is similar but the other tickets talk about scenarios where no node_modules are present. This request was more in line with having a --metadata style flag whereby the overall metadata for the project level gets captured at the start of the file.

**Comment by helio-frota** [comment]
@lgriffin thanks !

**Comment by helio-frota** [comment]
@lgriffin  how to reproduce:

`$ license-reporter --metadata`

```xml
<?xml version='1.0'?>
<licenseSummary>
    <project>szero</project>
    <version>1.0.0</version>
    <license>Apache-2.0</license>    <-----------------------
    <dependencies>
        <dependency>
            <packageName>node-builtins</packageName>
            <version>0.1.1</version>
            <licenses>
                <license>
                    <name>Apache License 2.0</name>
                    <url>http://www.apache.org/licenses/LICENSE-2.0</url>
                </license>
            </licenses>
        </dependency>
        <dependency>
            <packageName>roi</packageName>
            <version>0.15.0</version>
            <licenses>
                <license>
                    <name>Apache License 2.0</name>
                    <url>http://www.apache.org/licenses/LICENSE-2.0</url>
                </license>
            </licenses>
        </dependency>
    </dependencies>
</licenseSummary>
```

inside empty project:

```
[hf@localhost aaa]$ license-reporter --metadata
<?xml version='1.0'?>
<licenseSummary>
    <project>aaa</project>
    <version>1.0.0</version>
    <license>ISC</license>
    <dependencies/>
</licenseSummary>
```
