### ISSUE TITLE
Ability to diff/visualize difference from previous license file(s)

### ISSUE THREAD

**Issue by kpiwko** [bucharest-gold/license-reporter#86]
### What

Provide a functionality that allows to easily spot changes - e.g. a transitive dependency that has recently been relicensed.

### Why

It is important to flag any changes in the project early on. It is hard to diff XMLs. So a way how to nicely diff output from previous version that could be integration into a CI pipeline is very usufel

**Comment by helio-frota** [comment]
@kpiwko sorry for the late answer.
This issue seems related (in some way) to #189

**Comment by helio-frota** [comment]
closing to keep the focus on #189
