### ISSUE TITLE
Whitelisted license dep list contains all items from unknown license dep list

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#94]
When I run `license-reporter --file license.xml --all`, and I get two lists printed to stdout after the xml contents, some elements are in both lists (my intuition would be that things would be in one or the other). E.g. here's what I see:

```
========= WARNING UNKNOWN LICENSES ==========
name: colors , version: 0.6.2 , licenses: UNKNOWN
name: cycle , version: 1.0.3 , licenses: UNKNOWN
========= WARNING UNKNOWN LICENSES ==========
========= WARNING WHITE-LISTED LICENSES ==========
name: caseless , version: 0.11.0 , licenses: Apache-2.0
name: colors , version: 0.6.2 , licenses: UNKNOWN
name: cookie , version: 0.1.2 , licenses: MIT*
name: cryptiles , version: 2.0.5 , licenses: BSD-3-Clause
name: cycle , version: 1.0.3 , licenses: UNKNOWN
name: dateformat , version: 1.0.2 , licenses: MIT*
========= WARNING WHITE-LISTED LICENSES ==========
```

Note that `colors` and `cycle` are in both lists.

One thing that comes to mind is that this could be related to #90, if for some reason 'Custom' licenses were previously going to the white list, but now are reporting as 'UNKNOWN'. I could be way off with that though!

**Comment by danbev** [comment]
@grdryn Thanks Ger, this was indeed because of #90 which I've reverted and will revisit it later.

**Comment by danbev** [comment]
Opened #96 for this issue.
