### ISSUE TITLE
Something strange happens with dependencies which have a non x.y.z version string

### ISSUE THREAD

**Issue by grdryn** [bucharest-gold/license-reporter#99]
I _think_ the reason for this strange behaviour is related to the version string.

Example: the [ups-admin-ui](https://www.npmjs.com/package/ups-admin-ui) version is `1.1.4-10`. My package depends on this module, and when I run `license-reporter --file license.xml --all`, I see the following oddities:

- Version string is truncated to `1.1.4`, both in the xml file, and in the warning list outputs that follow it in stdout
- Even though the license is detected correctly as `Apache-2.0`, the dependency shows up in both the "UNKNOWN LICENSES" list, and the "WHITE-LISTED LICENSES" list.

**Comment by danbev** [comment]
Opened https://github.com/bucharest-gold/license-reporter/pull/102 for this issue.
